#
# Copyright 2016, Data 61
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(D61_BSD)
#

resolver: ghc-7.10.3

local-bin-path: .

extra-deps:
  - MissingH-1.3.0.2
  - base-compat-0.9.0
  - mtl-2.2.1
  - parsec-3.1.11
  - split-0.2.3.1
  - HUnit-1.5.0.0
  - hslogger-1.2.10
  - network-2.6.3.1
  - old-locale-1.0.0.7
  - old-time-1.1.0.3
  - random-1.1
  - regex-compat-0.95.1
  - text-1.2.2.1
  - call-stack-0.1.0
  - regex-base-0.93.2
  - regex-posix-0.95.2
